# -*- coding: utf-8 -*-
"""p1-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Obrv-keCUrmhHA6Mv-1XNe9LAAI3IdxN
"""

#p1-1.py
import pandas as pd
import sys
import matplotlib.pyplot as plt
import read

def main():
  #para leer los argumentos del comando en bash
  if len(sys.argv) != 2:
    print("forma de uso de este archivo: python p1.py "archivo.csv")
    sys.exit(1) #código de terminacion de programa por error tipo 1 (convencional)
  archivo = sys.argv[1]
  #cargar datos del archivo csv

  primera_columna, columnas_restantes = read(archivo)
  print("Primera columna", primera_columna[:5])

  for i, columna in enumerate(columnas_restantes, start=2):
    print(f"Columna {i}: {columna[:5]}")