# -*- coding: utf-8 -*-
"""p1-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKQv6n7goNwk5ww_nH-CcuMRHTYi8yas
"""

#p1-2.py
import sys
from plot import plot1D, plot2D
import matplotlib.pyplot as plt

def main():
  if len(sys.argv) != 3:
    print("Uso: python p1-2.py 'out1d.png' 'out2d.png'")
    sys.exit(1)

  out1d = sys.argv[1]
  out2d = sys.argv[2]

# datos necesarios para plot1D
  t1 = [0, 1, 2, 3, 4, 5, 6, 7, 8]
  x1 = [0, 1, -1, 1, -1, 1, -1, 1, -1]

  plot1D(t1, x1, "Tiempo", "Posición en Y")
  plt.savefig(out1d)
  print(f"Gráfico 1D guardado en {out1d}")

  #datos plot2D
  t2 = [0.0, 0.33, 0.66, 0.99, 1.32, 1.65, 1.98, 2.31, 2.64, 2.98,
          3.31, 3.64, 3.97, 4.30, 4.63, 4.96, 5.29, 5.62, 5.95, 6.28]
  x2 = [1.0, 0.95, 0.79, 0.55, 0.25, -0.08, -0.4, -0.68, -0.88, -0.99,
          -0.99, -0.88, -0.68, -0.4, -0.08, 0.25, 0.55, 0.79, 0.95, 1.0]
  y2 = [0.00, 0.325, 0.614, 0.837, 0.969, 0.997, 0.916, 0.736, 0.476, 0.165,
          -0.165, -0.476, -0.736, -0.916, -0.997, -0.969, -0.837, -0.614, -0.325, -2.45e-16]

  plot2D(x2, y2, t2, "Posición en X", "Posición en Y")
  plt.savefig(out2d)
  print(f"Gráfico 2D guardado en {out2d}")