# -*- coding: utf-8 -*-
"""plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgkaVcKKk1stVnpMkXPzWg_SKj5Vp4FO
"""

#plot.py

import matplotlib.pyplot as plt

def plot1D(x, y, xlabel, ylabel)
  plt.figure()
  plt.plot(x, y, label=ylabel, color = "b")
  plt.xlabel(xlabel)
  plt.ylabel(ylabel)
  plt.title(f"{xlabel} vs {ylabel}")
  plt.legend()
  plt.grid(True)#cuadricula en grafico

def plot2D(x, y, c, xlabel, ylabel):
  plt.figure()
  plt.scatter(x, y, c=c, cmap="viridis")
  plt.colorbar(label="valor del campo")
  plt.xlabel(xlabel)
  plt.ylabel(ylabel)
  plt.title(f"{xlabel} vs {ylabel}")
  plt.grid(True)