# -*- coding: utf-8 -*-
"""read.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fk76DZLcX4sURbZOMWdFp2W0rGX1359N
"""

#read.py original
import pandas as pd

def read(filename):
  #ller archivo csv con pandas
  datos = pd.read_csv(filename)
  #obtener los datos de la primera columna
  primera_columna = datos.iloc[:, 0].tolist()

  if len(datos.columns) >= 1:
  #caso de las siguientes columnas
  columnas_restantes = [datos.iloc[:, i].tolist() for i in range(1, len(datos.columns))]
  #tambien puede ser asi:
  #columnas_restantes = []  # Crear una lista vacía para almacenar cada columna adicional
  #for i in range(1, len(datos.columns)):
    #columnas_restantes.append(datos.iloc[:, i].tolist())  # Añadir cada columna a la lista
  return primera_columna, columna_restantes

  else:
    #Raise, el programa se detiene en este punto y se genera mensaje de error ValueError lanza excepcion tipo valueerror
    raise ValueError("El archivo debe tener 2 o más columnas")